In [27]:
import numpy as np
np.random.seed(3148954390)

In [28]:
arr = np.random.random((4,3))
print(arr)

[[0.5750586  0.23533348 0.63871382]
 [0.20123823 0.02631137 0.73035307]
 [0.0040074  0.78377444 0.93347798]
 [0.57735861 0.35279109 0.34026705]]


In [29]:
c = arr[:,np.newaxis,:]
print(c)
print(c.shape)
print(c[0,0,1])

[[[0.5750586  0.23533348 0.63871382]]

 [[0.20123823 0.02631137 0.73035307]]

 [[0.0040074  0.78377444 0.93347798]]

 [[0.57735861 0.35279109 0.34026705]]]
(4, 1, 3)
0.23533348028648737


In [40]:
d = arr[:,np.newaxis,:]-np.zeros_like(arr)
print(d.shape)
print(d)

(4, 4, 3)
[[[0.5750586  0.23533348 0.63871382]
  [0.5750586  0.23533348 0.63871382]
  [0.5750586  0.23533348 0.63871382]
  [0.5750586  0.23533348 0.63871382]]

 [[0.20123823 0.02631137 0.73035307]
  [0.20123823 0.02631137 0.73035307]
  [0.20123823 0.02631137 0.73035307]
  [0.20123823 0.02631137 0.73035307]]

 [[0.0040074  0.78377444 0.93347798]
  [0.0040074  0.78377444 0.93347798]
  [0.0040074  0.78377444 0.93347798]
  [0.0040074  0.78377444 0.93347798]]

 [[0.57735861 0.35279109 0.34026705]
  [0.57735861 0.35279109 0.34026705]
  [0.57735861 0.35279109 0.34026705]
  [0.57735861 0.35279109 0.34026705]]]


In [33]:
print(d**2)

[[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [1.39741667e-01 4.36902420e-02 8.39775133e-03]
  [3.26099479e-01 3.00787487e-01 8.68859119e-02]
  [5.29005152e-06 1.37962907e-02 8.90704774e-02]]

 [[1.39741667e-01 4.36902420e-02 8.39775133e-03]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [3.89000032e-02 5.73750301e-01 4.12597321e-02]
  [1.41466539e-01 1.06589008e-01 1.52167103e-01]]

 [[3.26099479e-01 3.00787487e-01 8.68859119e-02]
  [3.89000032e-02 5.73750301e-01 4.12597321e-02]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [3.28731617e-01 1.85746646e-01 3.51899217e-01]]

 [[5.29005152e-06 1.37962907e-02 8.90704774e-02]
  [1.41466539e-01 1.06589008e-01 1.52167103e-01]
  [3.28731617e-01 1.85746646e-01 3.51899217e-01]
  [0.00000000e+00 0.00000000e+00 0.00000000e+00]]]


In [37]:
r = (d**2).sum(2)

In [38]:
print(r)

[[0.         0.19182966 0.71377288 0.10287206]
 [0.19182966 0.         0.65391004 0.40022265]
 [0.71377288 0.65391004 0.         0.86637748]
 [0.10287206 0.40022265 0.86637748 0.        ]]


In [39]:
r[np.triu_indices_from(r,1)]

array([0.19182966, 0.71377288, 0.10287206, 0.65391004, 0.40022265,
       0.86637748])