In [7]:
import numpy as np
np.random.seed(3148954390)

In [8]:
arr = np.random.random((3,3))
print(arr)

[[0.5750586  0.23533348 0.63871382]
 [0.20123823 0.02631137 0.73035307]
 [0.0040074  0.78377444 0.93347798]]


In [9]:
c = arr[:,np.newaxis,:]
print(c)
print(c.shape)
print(c[0,0,1])

[[[0.5750586  0.23533348 0.63871382]]

 [[0.20123823 0.02631137 0.73035307]]

 [[0.0040074  0.78377444 0.93347798]]]
(3, 1, 3)
0.23533348028648737


In [10]:
d = arr[:,np.newaxis,:]-np.zeros_like(arr)
print(d.shape)
print(d)

(3, 3, 3)
[[[0.5750586  0.23533348 0.63871382]
  [0.5750586  0.23533348 0.63871382]
  [0.5750586  0.23533348 0.63871382]]

 [[0.20123823 0.02631137 0.73035307]
  [0.20123823 0.02631137 0.73035307]
  [0.20123823 0.02631137 0.73035307]]

 [[0.0040074  0.78377444 0.93347798]
  [0.0040074  0.78377444 0.93347798]
  [0.0040074  0.78377444 0.93347798]]]


In [11]:
arr1 = np.zeros((3,3,3))
arr1[:,0,:] = arr
arr1[:,1,:] = arr
arr1[:,2,:] = arr

In [12]:
print(d**2)

[[[3.30692394e-01 5.53818469e-02 4.07955346e-01]
  [3.30692394e-01 5.53818469e-02 4.07955346e-01]
  [3.30692394e-01 5.53818469e-02 4.07955346e-01]]

 [[4.04968264e-02 6.92288267e-04 5.33415603e-01]
  [4.04968264e-02 6.92288267e-04 5.33415603e-01]
  [4.04968264e-02 6.92288267e-04 5.33415603e-01]]

 [[1.60592194e-05 6.14302373e-01 8.71381148e-01]
  [1.60592194e-05 6.14302373e-01 8.71381148e-01]
  [1.60592194e-05 6.14302373e-01 8.71381148e-01]]]


In [13]:
r = (d**2).sum(2)

In [14]:
print(r)

[[0.79402959 0.79402959 0.79402959]
 [0.57460472 0.57460472 0.57460472]
 [1.48569958 1.48569958 1.48569958]]


In [15]:
r[np.triu_indices_from(r,1)]

array([0.79402959, 0.79402959, 0.57460472])

: 