In [33]:
import numpy as np
from numpy.linalg import solve

In [18]:
A = np.array([[-6,3,0,-6],[4,-2,2,6],[2,3,-8,-3],[-7,-4,-3,8]],dtype = np.float64)

In [19]:
B = np.array([[-2],[-4],[-9],[1]],dtype = np.float64)

In [20]:
print(A)

[[-6.  3.  0. -6.]
 [ 4. -2.  2.  6.]
 [ 2.  3. -8. -3.]
 [-7. -4. -3.  8.]]


In [21]:
print(B)

[[-2.]
 [-4.]
 [-9.]
 [ 1.]]


In [23]:
A_inv = np.linalg.inv(A)


In [24]:
print(A_inv)

[[-0.10934744 -0.02380952  0.01587302 -0.05820106]
 [ 0.57671958  0.71428571  0.19047619 -0.03174603]
 [ 0.10229277  0.11904762 -0.07936508 -0.04232804]
 [ 0.23104056  0.38095238  0.07936508  0.04232804]]


In [30]:
sol = np.matmul(A_inv,B)
sol

array([[ 0.11287478],
       [-5.75661376],
       [-0.00881834],
       [-2.65784832]])

In [34]:
np_sol = solve(A,B)

In [35]:
np_sol

array([[ 0.11287478],
       [-5.75661376],
       [-0.00881834],
       [-2.65784832]])