In [28]:
import numpy as np

In [29]:
a = [x**2 for x in range(10)]
print(a)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [30]:
g = (x**2 for x in range(10))
print(g)

<generator object <genexpr> at 0x000001C9F225F920>


In [31]:
for item in g: print(item)

0
1
4
9
16
25
36
49
64
81


In [8]:

def linearSpace(l1,l2,n):

    h = (l2-l1)/(n-1)

    for x in range(n):
        yield from [l1+x*h]


In [14]:
np.linspace(0,5,100000000)

array([0.00000000e+00, 5.00000005e-08, 1.00000001e-07, ...,
       4.99999990e+00, 4.99999995e+00, 5.00000000e+00])

In [9]:
linearSpace(0,5,1000)

<generator object linearSpace at 0x000001C9DA1FA180>

In [15]:
#for val in linearSpace(0,5,1000): print(val)

In [25]:
t = linearSpace(0,2*np.pi, 10000)


In [ ]:
def integrate(f, g, l1, l2, sample, partition, **kwargs):
    if "startVal" in kwargs:
        startVal = kwargs["startVal"]
    else: startVal = 0

    for x in g:
        f

    

In [32]:
def factorial_recursive(n):
    if n<2: return 1
    return n*factorial_recursive(n-1)

In [ ]:
def factorial_tail_call(n,acc=1):
    if n<2: return acc
    return factorial_tail_call(n-1,acc*n)


In [ ]:
def factorial_iterative(n,*,acc=1):
    while n>1: (n,acc) = (n-1,acc*n)
    return acc

In [33]:
a = np.array([1,2,3,4,5,6])

In [34]:
b = a.reshape(3,2)

In [37]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [36]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [38]:
c = b.copy()
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [39]:
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
d = c.reshape(6)

In [43]:
print(d)

[1 2 3 4 5 6]


In [50]:
e = np.asfortranarray(c)

In [53]:
e.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [54]:
e.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [55]:
a = np.array([1,2,3,8])

In [56]:
anew = a[:,np.newaxis]

In [60]:
print(anew)

[[1]
 [2]
 [3]
 [8]]


In [57]:
a.shape

(4,)

In [58]:
anew.shape

(4, 1)

In [59]:
a-anew

array([[ 0,  1,  2,  7],
       [-1,  0,  1,  6],
       [-2, -1,  0,  5],
       [-7, -6, -5,  0]])

In [62]:
class Bird:
    def __init__(self, name) -> None:
        self.name = name

    def fly(self):
        print("Ok, I'm taking off")


class Sparrow(Bird):
    def __init__(self, name):
        super().__init__(name)

    def fly(self):
        print("I'm a sparrow")

In [65]:
Sparrow('Jack').fly()

I'm a sparrow


In [67]:
class Foo:
    def _bar1():
        print("this is class Foo's _bar1() \n")
    def __bar2():
        print("this is class Foo's __bar2()\n")
    def _test():
        Foo.__bar2()
# these work:
Foo._bar1()
Foo._test()
# this doesn't work; raises AttributeError
# Foo.__bar2()
# but this does:
Foo._Foo__bar2() # Python name mangling

this is class Foo's _bar1() 

this is class Foo's __bar2()

this is class Foo's __bar2()



--------------------------------------------------------------------------------
